version: 2
jobs:
  build:
    docker:
      - image: node:10.15
    steps:
      - checkout
      - run:
          name: Install dependencies
          working_directory: /
          command: |
            echo "> ${AWS_ACCESS_KEY_ID}"
            echo "> ${AWS_SECRET_ACCESS_KEY}"
