version: 2
jobs:
  build:
    docker:
      - image: node:10.15
    steps:
      - checkout
      - run:
          name: Install dependencies
          working_directory: /
          command: |
            echo 'export PATH=/root/.local/bin:$PATH' >> $BASH_ENV
            source $BASH_ENV
            apt-get -y -qq update
            apt-get -y -qq install python3.4
            curl -O https://bootstrap.pypa.io/get-pip.py
            python3 get-pip.py --user
            pip install awscli --upgrade --user
      - run: npm install
      - run:
          name: Deploy app
          command: |
            aws configure set aws_access_key_id value ${AWS_ACCESS_KEY_ID}
            aws configure set aws_secret_access_key value ${AWS_SECRET_ACCESS_KEY}
            npm run deploy:no-cli
