version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.15

    steps:
      - checkout
      - run:
          name: Install dependencies
          working_directory: /
          command: |
            apt-get -y -qq update
            apt-get -y -qq install python3.4-dev
            curl -O https://bootstrap.pypa.io/get-pip.py
            python3.4 get-pip.py --user
            pip install awscli --upgrade --user
      - run: npm install
      - run: npm run deploy
