export const API_HOST = ''
export const SOCKETIO_HOST = ''
export const LOCAL_DB = ''
export const PUBLIC_VAPID_KEY = ''
export const NODE_ENV = ''
export const LINK_URL_PREFIX = ''
export const JWT = ''
export const PN = ''
