export const UPLOAD_HOST = 'http://localhost:8181/api/upload'
export const AUTH_HOST = 'http://localhost:8181/api/auth'
export const GRAPHQL_HOST = 'http://localhost:8181/graphql'
export const API_HOST = 'http://localhost:8181'
export const SOCKETIO_HOST = 'http://localhost:3001'
export const LOCAL_DB = 'weekday'
export const PUBLIC_VAPID_KEY = 'BK-o1CaPiLRUYWahx8VbyocJwrdmbdAYE3qPG17rZ6kjOWduL6-P6UFu5yxfH4fw4KhGzxmnbYAMeSAVU4zshkk'
export const NODE_ENV = 'development'
